INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Flooded access route near the east ridge', 'Heavy rain has cut off the main access route and created a hazardous detour for commuters.', 'mock-user-1', 'Alicia Lee', id, 'Open', 'Sama', 'Orani', 'Bataan', 'East ridge access route, Orani, Bataan', 120.5362, 14.8011, '2026-05-18 08:30:00', '2026-05-18 08:30:00' FROM categories WHERE slug = 'flooding' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Flooded access route near the east ridge');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Power outage affecting downtown corridor', 'Several blocks remain without stable power after a transformer failure early this morning.', 'mock-user-2', 'Jordan Miles', id, 'Pending', 'Poblacion', 'Balanga', 'Bataan', 'Downtown corridor, Balanga, Bataan', 120.5370, 14.6760, '2026-05-17 18:10:00', '2026-05-17 18:10:00' FROM categories WHERE slug = 'power-outage' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Power outage affecting downtown corridor');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Road debris near the coastal junction', 'A truck spill has left debris scattered across the coastal intersection.', 'mock-user-3', 'Rina Shah', id, 'Open', 'Wawa', 'Orion', 'Bataan', 'Coastal junction, Orion, Bataan', 120.5815, 14.6205, '2026-05-16 14:45:00', '2026-05-16 14:45:00' FROM categories WHERE slug = 'road-hazard' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Road debris near the coastal junction');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Blocked drainage along national highway', 'Standing water is forming beside the northbound lane because of blocked drainage.', 'mock-user-4', 'Marco Santos', id, 'Resolved', 'Poblacion', 'Hermosa', 'Bataan', 'National Highway, Hermosa, Bataan', 120.5020, 14.8310, '2026-05-15 11:20:00', '2026-05-15 16:00:00' FROM categories WHERE slug = 'flooding' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Blocked drainage along national highway');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Temporary lane closure for bridge repairs', 'One lane is closed while crews inspect and repair the bridge approach.', 'mock-user-5', 'Nina Cruz', id, 'Pending', 'Santo Cristo', 'Dinalupihan', 'Bataan', 'Bridge approach, Dinalupihan, Bataan', 120.4650, 14.8780, '2026-05-14 09:00:00', '2026-05-14 09:00:00' FROM categories WHERE slug = 'roadworks' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Temporary lane closure for bridge repairs');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Speeding observed near school zone', 'Drivers are moving too quickly during school arrival and dismissal hours.', 'mock-user-6', 'Leo Garcia', id, 'Open', 'Dangcol', 'Balanga', 'Bataan', 'School zone, Balanga, Bataan', 120.5460, 14.6800, '2026-05-13 07:40:00', '2026-05-13 07:40:00' FROM categories WHERE slug = 'traffic-violation' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Speeding observed near school zone');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Fallen tree blocking side street', 'A fallen tree is blocking both directions on a residential side street.', 'mock-user-7', 'Paolo Reyes', id, 'Closed', 'Cupang Proper', 'Balanga', 'Bataan', 'Cupang side street, Balanga, Bataan', 120.5440, 14.6890, '2026-05-12 16:25:00', '2026-05-12 19:10:00' FROM categories WHERE slug = 'road-hazard' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Fallen tree blocking side street');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Roadworks causing morning congestion', 'Utility work has reduced the road to one lane and caused a long queue.', 'mock-user-8', 'Mia Torres', id, 'Open', 'Poblacion', 'Limay', 'Bataan', 'Main road, Limay, Bataan', 120.5980, 14.5610, '2026-05-11 08:05:00', '2026-05-11 08:05:00' FROM categories WHERE slug = 'roadworks' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Roadworks causing morning congestion');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Unlit intersection after sunset', 'Streetlights are out at a busy intersection, reducing visibility for pedestrians.', 'mock-user-9', 'Ana Villanueva', id, 'Pending', 'Poblacion', 'Mariveles', 'Bataan', 'Central intersection, Mariveles, Bataan', 120.4870, 14.4350, '2026-05-10 19:30:00', '2026-05-10 19:30:00' FROM categories WHERE slug = 'road-hazard' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Unlit intersection after sunset');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Illegal parking beside public market', 'Vehicles are blocking the loading area and forcing pedestrians into traffic.', 'mock-user-10', 'Omar Diaz', id, 'Open', 'Poblacion', 'Bataan', 'Bataan', 'Public market, Bataan', 120.5375, 14.6750, '2026-05-09 12:15:00', '2026-05-09 12:15:00' FROM categories WHERE slug = 'traffic-violation' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Illegal parking beside public market');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Flash flooding near creek crossing', 'Water rises quickly across the creek crossing after heavy afternoon rain.', 'mock-user-11', 'Bea Lim', id, 'Resolved', 'Mabiga', 'Hermosa', 'Bataan', 'Creek crossing, Hermosa, Bataan', 120.4900, 14.8150, '2026-05-08 15:50:00', '2026-05-08 18:20:00' FROM categories WHERE slug = 'flooding' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Flash flooding near creek crossing');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Damaged traffic signal at junction', 'The traffic signal is stuck on red and officers are directing vehicles manually.', 'mock-user-12', 'Carlo Mendoza', id, 'Open', 'Tenejero', 'Balanga', 'Bataan', 'Junction near Tenejero, Balanga, Bataan', 120.5500, 14.6900, '2026-05-07 17:05:00', '2026-05-07 17:05:00' FROM categories WHERE slug = 'traffic-violation' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Damaged traffic signal at junction');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Shoulder erosion on mountain route', 'The road shoulder is eroding and leaving a narrow passage for vehicles.', 'mock-user-13', 'Ivy Navarro', id, 'Pending', 'Kinarut', 'Bagac', 'Bataan', 'Mountain route, Bagac, Bataan', 120.4110, 14.5960, '2026-05-06 10:30:00', '2026-05-06 10:30:00' FROM categories WHERE slug = 'road-hazard' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Shoulder erosion on mountain route');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Water main work near terminal', 'Construction equipment is occupying the outer lane near the transport terminal.', 'mock-user-14', 'Jules Aquino', id, 'Closed', 'Poblacion', 'Orani', 'Bataan', 'Transport terminal, Orani, Bataan', 120.5360, 14.8000, '2026-05-05 13:40:00', '2026-05-05 17:00:00' FROM categories WHERE slug = 'roadworks' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Water main work near terminal');
INSERT OR IGNORE INTO reports (title, description, author_id, author_name, category_id, status, barangay, city, province, resolved_address, longitude, latitude, created_at, updated_at)
SELECT 'Motorcycle lane violation hotspot', 'Frequent motorcycle violations are creating conflicts near the city center.', 'mock-user-15', 'Tess Flores', id, 'Open', 'Poblacion', 'Dinalupihan', 'Bataan', 'City center, Dinalupihan, Bataan', 120.4680, 14.8785, '2026-05-04 09:15:00', '2026-05-04 09:15:00' FROM categories WHERE slug = 'traffic-violation' AND NOT EXISTS (SELECT 1 FROM reports WHERE title = 'Motorcycle lane violation hotspot');
